#!/bin/bash
set -euo pipefail

ENV_FILE=".env"
cd "$(dirname "$0")/.."

if [ -f "$ENV_FILE" ]; then
  echo "⚠  $ENV_FILE already exists. Overwrite? (y/N)"
  read -r answer
  if [ "$answer" != "y" ]; then
    echo "Aborted."
    exit 1
  fi
fi

echo "Generating secrets..."

# VAPID keys via openssl + python3
TMPDIR=$(mktemp -d)
openssl ecparam -genkey -name prime256v1 -noout -out "$TMPDIR/ec.pem" 2>/dev/null
eval "$(python3 -c "
import subprocess, base64, sys

result = subprocess.run(['openssl', 'ec', '-in', '$TMPDIR/ec.pem', '-text', '-noout'], capture_output=True, text=True)
lines = result.stdout

in_priv, priv_hex = False, ''
for line in lines.splitlines():
    if line.startswith('priv:'): in_priv = True; continue
    if line.startswith('pub:'): in_priv = False
    if in_priv: priv_hex += line.strip().replace(':', '').replace(' ', '')

in_pub, pub_hex = False, ''
for line in lines.splitlines():
    if line.startswith('pub:'): in_pub = True; continue
    if line.startswith('ASN1'): in_pub = False
    if in_pub: pub_hex += line.strip().replace(':', '').replace(' ', '')

priv_bytes = bytes.fromhex(priv_hex)
pub_bytes = bytes.fromhex(pub_hex)
print(f'VAPID_PRIVATE_KEY={base64.urlsafe_b64encode(priv_bytes).rstrip(b\"=\").decode()}')
print(f'VAPID_PUBLIC_KEY={base64.urlsafe_b64encode(pub_bytes).rstrip(b\"=\").decode()}')
")"
rm -rf "$TMPDIR"

cat > "$ENV_FILE" << EOF
# =============================================
# Cukkr — Docker Compose Environment Variables
# Auto-generated by scripts/setup.sh
# =============================================

# Database
DB_PASSWORD=cukkr
DB_PORT=5432

# Backend API
BACKEND_PORT=3000

# Better Auth
BETTER_AUTH_SECRET=$(openssl rand -base64 32 | tr -d '\n')

# Web (Next.js landing)
WEB_PORT=3001

# Frontend (Expo web)
FRONTEND_PORT=8080

# Expo
EXPO_PUBLIC_ENV_CODE=development

# Strapi CMS
STRAPI_PORT=1337
STRAPI_APP_KEYS=$(openssl rand -hex 16),$(openssl rand -hex 16)
STRAPI_API_TOKEN_SALT=$(openssl rand -hex 32)
STRAPI_ADMIN_JWT_SECRET=$(openssl rand -hex 32)
STRAPI_TRANSFER_TOKEN_SALT=$(openssl rand -hex 32)
STRAPI_JWT_SECRET=$(openssl rand -hex 32)
STRAPI_ENCRYPTION_KEY=$(openssl rand -hex 32)
STRAPI_API_TOKEN=

# Next.js
NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=$(openssl rand -hex 32)

# SMTP (optional — kosong aman untuk dev)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_USER=
SMTP_PASS=
SMTP_SECURE=true

# Walk-In PIN — minimal 32 karakter
WALK_IN_TOKEN_SECRET=$(openssl rand -hex 32)

# Web Push (VAPID)
VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
VAPID_EMAIL=mailto:support@cukkr.com

# S3-compatible Storage (external)
STORAGE_ENDPOINT=http://localhost:9000
STORAGE_BUCKET=cukkr
STORAGE_ACCESS_KEY=$(openssl rand -hex 16)
STORAGE_SECRET_KEY=$(openssl rand -hex 32)
EOF

echo "✓ All secrets generated and written to .env"
echo ""
echo "Next step: docker compose up --build"
